spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/DueTo-Database
    username: DueTo
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
server:
  servlet:
    session:
      timeout: 1d
      cookie:
        http-only: true
        secure: true
secrets:
  JWT_SECRET: SecretKeyToGenJWTs